services:
  database:
    image: postgres:${POSTGRES_VERSION:-18.3}
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password