springdoc.group-configs[0].group=person-management
springdoc.group-configs[0].displayName=Person Management
springdoc.group-configs[0].paths-to-match=/person/**

springdoc.group-configs[1].group=task-management
springdoc.group-configs[1].displayName=Task Management
springdoc.group-configs[1].paths-to-match=/task/**

springdoc.group-configs[2].group=tag-management
springdoc.group-configs[2].displayName=Tag Management
springdoc.group-configs[2].paths-to-match=/tag/**

springdoc.group-configs[3].group=version-management
springdoc.group-configs[3].displayName=Version Management
springdoc.group-configs[3].paths-to-match=/version/**

springdoc.group-configs[4].group=note-management
springdoc.group-configs[4].displayName=Note Management
springdoc.group-configs[4].paths-to-match=/note/**

springdoc.group-configs[5].group=all
springdoc.group-configs[5].displayName=All
springdoc.group-configs[5].paths-to-match=/**
