spring.jpa.hibernate.ddl-auto=create-drop

spring.main.web-application-type=none

spring.main.banner-mode=off

spring.jpa.open-in-view=false

# Enable Hibernate batch processing
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.batch_versioned_data=true

logging.level.root=warn
logging.level.org.springframework=error
logging.level.org.hibernate=error
logging.level.org.testcontainers=error

logging.level.org.testcontainers.utility=ERROR
logging.level.org.testcontainers.dockerclient=ERROR
logging.level.org.testcontainers.containers=ERROR
logging.level.org.testcontainers.lifecycle=ERROR